name: bygul CI and PyPI Release

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  testsuite:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: bioconda,conda-forge
          channel-priority: true
          python-version: '3.10'
          activate-environment: test

      - name: Install
        shell: bash -l {0}
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda config --add channels bioconda
          conda config --add channels conda-forge          
          conda install --yes --file ci/conda_requirements.txt
          pip install -e . --no-deps 
          
      - name: Test
        shell: bash -l {0}
        run: |
          conda activate test
          make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Lint
        run: |
          pip install -q flake8
          make lint

  pypi-publish:
    name: Publish release to PyPI
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bygul
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
